### ISSUE TITLE
Unexpected keyword argument 'rng' in smac and pyrfr==0.7.2

### ISSUE THREAD

**Issue by sslavian812** [automl/SMAC3#365]
Hi!
I'm new to python and smac. I try to run smac to optimize hyperparameters for a clustering algorithm.

Consider the following code.
```
    smac = SMAC(scenario=my_scenario, rng=np.random.RandomState(my_seed), tae_runner=my_run)
    parameters = smac.optimize()
```

I use `smac==0.6.0` and `pynisher==0.4` as suggested here: https://github.com/automl/auto-sklearn/issues/384#issuecomment-355039165. 
Got the error:
```
Traceback (most recent call last):
. . .
  File "/nfs/home/vshalamov/WORK/MultiClustering/ThreadsB.py", line 158, in run
    self.parameters = self.smac.optimize()
  File "/nfs/home/vshalamov/WORK/environment/multi-clustering-environment/lib/python3.4/site-packages/smac/facade/smac_facade.py", line 365, in optimize
    incumbent = self.solver.run()
  File "/nfs/home/vshalamov/WORK/environment/multi-clustering-environment/lib/python3.4/site-packages/smac/optimizer/smbo.py", line 129, in run
    self.incumbent = self.initial_design.run()
  File "/nfs/home/vshalamov/WORK/environment/multi-clustering-environment/lib/python3.4/site-packages/smac/initial_design/single_config_initial_design.py", line 82, in run
    "0"))
  File "/nfs/home/vshalamov/WORK/environment/multi-clustering-environment/lib/python3.4/site-packages/smac/tae/execute_ta_run.py", line 168, in start
    instance_specific=instance_specific)
  File "/nfs/home/vshalamov/WORK/environment/multi-clustering-environment/lib/python3.4/site-packages/smac/tae/execute_func.py", line 156, in run
    runtime = float(obj.wall_clock_time)
AttributeError: 'function_wrapper' object has no attribute 'wall_clock_time'
```

I found the following code in the `smac`. Seems, that `enforce_limit` produces an object without wall_clock_time attribute:
```
if self.use_pynisher:
    obj = pynisher.enforce_limits(**arguments)(self.ta)
    . . .
    runtime = float(obj.wall_clock_time)
```

I tried to upgrade pynisher to 0.4.1 or 0.4.2, according to smac 6.0 requirements: https://github.com/automl/SMAC3/blob/9b8524a9b8011f88231e7cc911b3f198d6f3fd70/requirements.txt

After that, I started getting another error:
```
  . . .
  File "/nfs/home/vshalamov/WORK/MultiClustering/ThreadsEx.py", line 63, in run
    self.parameters = smac.optimize()
  File "/nfs/home/vshalamov/WORK/environment/multi-clustering-environment/lib/python3.4/site-packages/smac/facade/smac_facade.py", line 365, in optimize
    incumbent = self.solver.run()
  File "/nfs/home/vshalamov/WORK/environment/multi-clustering-environment/lib/python3.4/site-packages/smac/optimizer/smbo.py", line 148, in run
    challengers = self.choose_next(X, Y)
  File "/nfs/home/vshalamov/WORK/environment/multi-clustering-environment/lib/python3.4/site-packages/smac/optimizer/smbo.py", line 216, in choose_next
    self.model.train(X, Y)
  File "/nfs/home/vshalamov/WORK/environment/multi-clustering-environment/lib/python3.4/site-packages/smac/epm/base_epm.py", line 111, in train
    return self._train(X, Y)
  File "/nfs/home/vshalamov/WORK/environment/multi-clustering-environment/lib/python3.4/site-packages/smac/epm/rf_with_instances.py", line 142, in _train
    self.rf.fit(data, rng=self.rng)
TypeError: fit() got an unexpected keyword argument 'rng'
```

As suggested in https://github.com/automl/auto-sklearn/issues/342 I tried different versions of `pyrfr` (`0.5.0`, `0.6.0`, `0.6.1`, `0.7.2`) , but nothing changed.

I believe that I've satisfied all requirements for smac==0.6.0: https://github.com/automl/SMAC3/blob/9b8524a9b8011f88231e7cc911b3f198d6f3fd70/requirements.txt

 `pip list` output:

<details>
  <summary>Click to expand . . .</summary>

```sh
alabaster (0.7.10)
argparse (1.4.0)
auto-sklearn (0.2.1)
Babel (2.5.1)
certifi (2017.11.5)
chardet (3.0.4)
ConfigSpace (0.3.8)
cycler (0.10.0)
Cython (0.27.3)
docutils (0.14)
idna (2.6)
imagesize (0.7.1)
Jinja2 (2.10)
joblib (0.11)
liac-arff (2.1.1)
lockfile (0.12.2)
MarkupSafe (1.0)
matplotlib (2.1.0)
nose (1.3.7)
numpy (1.13.3)
pandas (0.21.0)
pip (1.5.4)
psutil (5.4.3)
Pygments (2.2.0)
pynisher (0.4.1)
pyparsing (2.2.0)
pyrfr (0.7.2)
python-dateutil (2.6.1)
pytz (2017.3)
PyYAML (3.12)
requests (2.18.4)
scikit-learn (0.18.2)
scipy (1.0.0)
setuptools (2.2)
six (1.11.0)
sklearn (0.0)
smac (0.6.0)
snowballstemmer (1.2.1)
Sphinx (1.6.5)
sphinx-rtd-theme (0.2.4)
sphinxcontrib-websupport (1.0.1)
typing (3.6.2)
urllib3 (1.22)
```
</details>

Any idea what is happening?

**Comment by mfeurer** [comment]
The issue you're likely facing is most likely https://github.com/automl/random_forest_run/issues/35, and a simple `pip uninstall pyrfr` or `pip install pyrfr==0.6.0` won't do the job. Please repeat the uninstall command until it fails before installing a different version of the random forest. Also, if you're using only SMAC, you can use the latest version. Furthermore, there's a new release of auto-sklearn which uses the latest SMAC version, too.

**Comment by sslavian812** [comment]
I've already seen a problem about `pip uninstall pyrfr` leaving files behind. I used `rm -r` to remove `pyrfr` completely. Repeating `pip uninstall pyrfr` several times removes pyrfr too.

Nothing changed: I'm getting `TypeError: fit() got an unexpected keyword argument 'rng'` error with all versions of `pyrfr` tried above.  
Which version of `prfr` are you using exactly?

`Smac 8.0` and it's dependencies https://github.com/automl/SMAC3/blob/56a5af9e3666ae54f7c126b62ae44852af65842d/requirements.txt

give me the same error:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  . . .
  File "/nfs/home/vshalamov/WORK/MultiClustering/ThreadsEx.py", line 63, in run
    self.parameters = smac.optimize()
  File "/nfs/home/vshalamov/WORK/environment/hydra-multi-clustering/lib/python3.4/site-packages/smac/facade/smac_facade.py", line 400, in optimize
    incumbent = self.solver.run()
  File "/nfs/home/vshalamov/WORK/environment/hydra-multi-clustering/lib/python3.4/site-packages/smac/optimizer/smbo.py", line 180, in run
    challengers = self.choose_next(X, Y)
  File "/nfs/home/vshalamov/WORK/environment/hydra-multi-clustering/lib/python3.4/site-packages/smac/optimizer/smbo.py", line 241, in choose_next
    self.model.train(X, Y)
  File "/nfs/home/vshalamov/WORK/environment/hydra-multi-clustering/lib/python3.4/site-packages/smac/epm/base_epm.py", line 111, in train
    return self._train(X, Y)
  File "/nfs/home/vshalamov/WORK/environment/hydra-multi-clustering/lib/python3.4/site-packages/smac/epm/rf_with_instances.py", line 142, in _train
    self.rf.fit(data, rng=self.rng)
TypeError: fit() got an unexpected keyword argument 'rng'
```

pip list output:
<details>
  <summary>Click to expand . . .</summary>

```sh
alabaster (0.7.10)
argparse (1.4.0)
Babel (2.5.1)
certifi (2017.11.5)
chardet (3.0.4)
ConfigSpace (0.4.3)
Cython (0.27.3)
docutils (0.14)
idna (2.6)
imagesize (0.7.1)
Jinja2 (2.10)
joblib (0.11)
MarkupSafe (1.0)
numpy (1.13.3)
pandas (0.22.0)
pip (1.5.4)
psutil (5.4.3)
Pygments (2.2.0)
pynisher (0.4.1)
pyparsing (2.2.0)
pyrfr (0.7.2)
python-dateutil (2.6.1)
pytz (2017.3)
requests (2.18.4)
scikit-learn (0.18)
scipy (0.18.1)
setuptools (2.2)
six (1.11.0)
smac (0.8.0)
snowballstemmer (1.2.1)
Sphinx (1.6.5)
sphinx-rtd-theme (0.2.4)
sphinxcontrib-websupport (1.0.1)
typing (3.6.2)
urllib3 (1.22)
```
</details>

**Comment by mfeurer** [comment]
The latest version, which is 0.7.2. Could you please open ipython and paste the output of:
```python
import pyrfr
print(pyrfr.__version__)
```

**Comment by sslavian812** [comment]
```
$ python3
Python 3.4.3 (default, Nov 17 2016, 01:08:31)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyrfr
>>> print(pyrfr.__version__)
0.7.2
>>>

```

**Comment by mfeurer** [comment]
I must admit that I have no idea how this could happen. @sfalkner @mlindauer any ideas?

**Comment by sfalkner** [comment]
The problem is not the pyrfr code itself, it's some old SMAC code calling it, trying to pass in a rng object that was removed a while ago. Which version of SMAC are you running?

**Comment by chansonZ** [comment]
same error, auto-sklearn is the latest version 0.3.0 :
In [1]: import pyrfr

In [2]: print(pyrfr.__version__)
0.7.2

In [3]: import smac

In [4]: print(smac.__version__)
0.8.0

import ConfigSpace
In [2]: print(ConfigSpace.__version__)
0.4.3

**Comment by mfeurer** [comment]
Could you please post the output of:
```python
import pyrfr
print(pyrfr.__file__)
import smac
print(smac.__file__)
```
and a list of the files in your `site-packages` directory?

**Comment by chansonZ** [comment]
**in my docker:**
root@75fd6c4ec629:/# ipython
Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %cpaste
Pasting code; enter '--' alone on the line to stop or use Ctrl-D.
:import pyrfr
print(pyrfr.__file__)
import smac
print(smac.__file__):::
:--
/opt/conda/lib/python3.6/site-packages/pyrfr/__init__.py
/opt/conda/lib/python3.6/site-packages/smac/__init__.py

**Comment by mfeurer** [comment]
That's a different environment than the one for which you initially reproted the issue. Does the issue happen in this environment, too?

**Comment by chansonZ** [comment]
### # yes.
 File "/opt/conda/lib/python3.6/site-packages/autosklearn/estimators.py", line 400, in fit
    dataset_name=dataset_name)
  File "/opt/conda/lib/python3.6/site-packages/autosklearn/estimators.py", line 227, in fit
    self._automl.fit(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/autosklearn/automl.py", line 887, in fit
    return super().fit(X, y, task, metric, feat_type, dataset_name)
  File "/opt/conda/lib/python3.6/site-packages/autosklearn/automl.py", line 189, in fit
    return self._fit(loaded_data_manager, metric)
  File "/opt/conda/lib/python3.6/site-packages/autosklearn/automl.py", line 439, in _fit
    _proc_smac.run_smbo()
  File "/opt/conda/lib/python3.6/site-packages/autosklearn/smbo.py", line 501, in run_smbo
    smac.optimize()
  File "/opt/conda/lib/python3.6/site-packages/smac/facade/smac_facade.py", line 400, in optimize
    incumbent = self.solver.run()
  File "/opt/conda/lib/python3.6/site-packages/smac/optimizer/smbo.py", line 180, in run
    challengers = self.choose_next(X, Y)
  File "/opt/conda/lib/python3.6/site-packages/smac/optimizer/smbo.py", line 241, in choose_next
    self.model.train(X, Y)
  File "/opt/conda/lib/python3.6/site-packages/smac/epm/base_epm.py", line 111, in train
    return self._train(X, Y)
  File "/opt/conda/lib/python3.6/site-packages/smac/epm/rf_with_instances.py", line 142, in _train
    self.rf.fit(data, rng=self.rng)

**TypeError: fit() got an unexpected keyword argument 'rng'**

**Comment by sfalkner** [comment]
After digging into code again, the only way that this problem can show up is an old version of the random forest (pyrfr). The rng argument was added 10 month ago in version 0.5. There must be an old version of the package somewhere. There was an issue where you had to deinstall the package twice to actually remove it, so you might be affected by that.
Could you please try one of the two options

1. Deinstall pyrfr (twice) via pip uninstall

**Comment by yujiezeng** [comment]
I'm afraid this issue still shows after I trid "`pip uninstall pyrfr `and install the latest version via `pip install --upgrade pyrfr`

**Comment by mfeurer** [comment]
Could you please try uninstalling `pyrfr` multiple times?

**Comment by yujiezeng** [comment]
Yes, I have tried several times to uninstall `pyrfr`, here's the pip output:
`root@11:/home/SMAC3/examples/branin# pip3.5 uninstall pyrfr
Cannot uninstall requirement pyrfr, not installed`

**Comment by yujiezeng** [comment]
I simply changed `/home/yujiezeng/SMAC3/smac/epm/rf_with_instances.py",` line 142  from `self.rf.fit(data, rng=self.rng)`  into `self.rf.fit(data, self.rng)`  and now my SMAC works. I don't know what's the root reason though.

**Comment by mfeurer** [comment]
We're puzzled as well, sorry for not being of any help.

**Comment by mfeurer** [comment]
Actually, the original issue might still be open.

**Comment by sslavian812** [comment]
@yujiezeng Thank you for your brilliant fix! It helped me too.
I was facing this issue for long time on some of my machines (on some machines smac worked, though).

**Comment by RickVM** [comment]
I'm facing this issue too.
Unfortunately editing the code as suggested above does not fix the issue for me. i still get the following message:

`/opt/conda/lib/python3.6/site-packages/smac/epm/rf_with_instances.py in _train(self, X, y, **kwargs)
    140         self.rf.options = self.rf_opts
    141         data = self.__init_data_container(self.X, self.y)
--> 142         self.rf.fit(data, self.rng)
    143         return self
    144 

TypeError: fit() got an unexpected keyword argument 'rng'`

Working on smac 0.8.0 with pyrfr 0.7.3
Any suggestions?

**Comment by mlindauer** [comment]
We still cannot reproduce this error.
Does this issue still exists on your side?

**Comment by angellandros** [comment]
If by this error you mean "unexpected keyword argument 'rng'", then I could reproduce it. But, the error solved after removing the keyword from the function call: 
```python
self.rf.fit(data, self.rng)
```

BTW, you can take a look at my `pip freeze` output if you like to reproduce the error: 
[https://github.com/angellandros/ml4aad/blob/master/freeze.txt](https://github.com/angellandros/ml4aad/blob/master/freeze.txt)

**Comment by angellandros** [comment]
I use Ubuntu 14.04, with `Python3.6` installed as follows:
```shell
$ sudo add-apt-repository ppa:deadsnakes/ppa
$ sudo apt-get update
$ sudo apt-get install python3.6
$ sudo apt-get install python3.6-dev
$ sudo apt-get install python3.6-tk
```

I also installed `swig3.0` as follows (couldn't make thing work with the old `swig`):
```shell
$ sudo apt-get remove swig
$ sudo apt-get install swig3.0
$ sudo ln -s /usr/bin/swig3.0 /usr/bin/swig
```

After that installed a virtualenv (`virtualenv -v python3.6 venv`) and did these inside:
```shell
$ pip install Cython
$ pip install pyrfr==0.8.0 --no-cache
$ pip install numpy scipy sklearn matplotlib
$ pip install git+https://github.com/automl/SMAC3.git@development
```

My `gcc` version is:
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.3' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
```

If it is of any use, I have zipped and uploaded my `venv` folder [here](https://drive.google.com/file/d/1Iph2glBTP-YXvc-uADMhWlpfUHmpLe4J/view?usp=sharing). I can also bring my laptop to the ML4AAD lab, if it's useful.

**Comment by sfalkner** [comment]
That is indeed puzzling. It's almost identical to the travis-ci setup where I run the unit tests:
https://travis-ci.org/automl/random_forest_run
Could you please check if you can find the difference between your system and the travis-ci VM that runs the unit-tests?

**Comment by peterz3g** [comment]
/opt/conda/lib/python3.6/site-packages/smac/epm/rf_with_instances.py in _train(self, X, y, **kwargs)
    140         self.rf.options = self.rf_opts
    141         data = self.__init_data_container(self.X, self.y)
--> 142         self.rf.fit(data, rng=self.rng)
    143         return self
    144 

TypeError: fit() got an unexpected keyword argument 'rng'
#############################################
# pip list| grep  pyrfr
pyrfr                              0.7.4   

the same issue with pyrfr 0.7.4

**Comment by zhouzhen1** [comment]
Also got this issue and studied it today: Those who report this error probably have an old swig version and which generates a fit(self, *args) signature for pyrfr. According to SWIG changelog you need at least swig 3.0.3 to get named arguments. 

According to http://www.swig.org/Release/CHANGES
```
2014-10-28: vadz
            [Python] Patch #201 The generated .py file no longer uses *args for all Python parameters.
            Instead, the parameters are named using the C++ parameter names.

            "compactdefaultargs" feature can be enabled to restore the old behaviour.

            *** POTENTIAL INCOMPATIBILITY ***
```

**Comment by mfeurer** [comment]
Closing this as there has been no activity for more than 2 years and we have the pyrfr at version 0.8
