### ISSUE TITLE
Cannot import classes from SMAC3 - "cannot import name <name> from smac" 

### ISSUE THREAD

**Issue by JuliaWasala** [automl/SMAC3#891]
#### Description
I wanted to follow the tutorial on SVM: https://automl.github.io/SMAC3/main/examples/1_basics/2_svm_cv.html#sphx-glr-examples-1-basics-2-svm-cv-py, but when I run:
`from smac import HyperparameterOptimizationFacade,Scenario` I get the following error: `ImportError: cannot import name 'HyperparameterOptimizationFacade' from 'smac' (/home/julia/miniconda3/envs/methane_env/lib/python3.9/site-packages/smac/__init__.py)`
I inspected the smac folder in the conda env, and found the classes I need there. I am able to import them with:
```
from smac.facade.smac_hpo_facade import SMAC4HPO
from smac.scenario.scenario import Scenario
```
However, I don't think that's how it's supposed to be -- I think the __init__ files are missing the imports. 

#### Steps/Code to Reproduce
I installed SMAC following the instructions in the documentation by (1) installing dependencies with conda, (2) `pip install smac`. Then import the modules in python notebook.

#### Versions
Running `smac.__version__` raises the error `AttributeError: module 'smac' has no attribute '__version__'`

**Comment by JuliaWasala** [comment]
ok, I think I have figured it out: both pip and conda install install the old version, which does not match the version that's automatically opened in the documentation. It would be nice if it could be indicated more clearly.

**Comment by JuliaWasala** [comment]
tried something else: clone the repository, `git checkout v2.0.0-alpha.2`, `pip install -e .`, import & version check still not working.

**Comment by eddiebergman** [comment]
Hi @JuliaWasala,

Yup the version of SMAC we are using now is actually `>=1.2,<1.3` which SMAC no longer even has documentation for. SMAC is getting a massive rewrite and is still unstable but we've started working on porting over to the `2.0.0` version which is still in alpha. This also requires updating sklearn.

As these are both core parts of auto-sklearn, unfortunatly it's not as simple as update requirements and update the names, our meta-learning is all based on pre `1.0.0` sklearn and SMAC's running and interface has changed drastically. These changes will unfortunatly take a while and there's not much I can offer you in the meantime :/

I've linked the relevant branches if you want to keep track of this issue.

**Comment by renesass** [comment]
Hey,

you can find the documentation of v1.4 [here](https://automl.github.io/SMAC3/v1.4.0/). As Eddie said, SMAC is massively under construction so that multi-objective, multi-fidelity, and multi-threading is supported natively with all options.
We actually have the implementation already ready on [this branch](https://github.com/automl/SMAC3/tree/intensifier) but we still need to write many tests. Sorry for the inconvenience.

**Comment by JuliaWasala** [comment]
okay, thanks for the updates! I was confused because when you go to the docs, it defaults to version 2.0.0.a2.
